version: 2.1

orbs:
   heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch
jobs:
  build:
    docker:
      - image: circleci/node:14.15.4
    parallelism: 1
    working_directory: ~/rossta/connect-four-vue
    steps:
      - checkout
      - attach_workspace:
          at: ~/rossta/connect-four-vue
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: 
          name: install
          command: npm install --no-progress --non-interactive --silent --pure-lockfile
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: 
            - dist